# Generated by Django 2.0.1 on 2018-01-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180104_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Don', 'Don'), ('Doña', 'Doña'), ('Señor', 'Señor'), ('Señora', 'Señora'), ('Señorita', 'Señorita')], max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('country_of_residence', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True, default='User bio')),
                ('is_conflict_participant', models.BooleanField(default=False)),
                ('is_conflict_victim', models.BooleanField(default=False)),
                ('is_living_in_conflict_zone', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
