# Generated by Django 2.0.1 on 2018-01-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180104_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
