# Generated by Django 2.0.1 on 2018-01-11 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20180107_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_conflict_participant',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_conflict_victim',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_living_in_conflict_zone',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('Don', 'Don'), ('Doña', 'Doña'), ('Señor', 'Señor'), ('Señora', 'Señora'), ('Señorita', 'Señorita')], default='Don', max_length=50),
        ),
        migrations.AddField(
            model_name='like',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thread'),
        ),
    ]
