# Generated by Django 2.0.1 on 2018-01-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dislike'),
        ('app', '0009_auto_20180112_2223'),
    ]

    operations = [
    ]
