# Generated by Django 2.0.1 on 2018-01-22 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20180122_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceLike',
            new_name='ExperiencesDislike',
        ),
        migrations.RenameModel(
            old_name='ExperienceDislike',
            new_name='ExperiencesLike',
        ),
    ]
