# Generated by Django 2.0.1 on 2018-02-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180204_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.ExperienceTag'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.ThreadTag'),
        ),
    ]
