
# Generated by Django 2.0.1 on 2018-02-16 03:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20180216_0103'),
        ('app', '0016_auto_20180215_0416'),
    ]

    operations = [
    ]
