# Generated by Django 2.0.1 on 2018-02-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180215_0416'),
        ('app', '0015_auto_20180215_0325'),
    ]

    operations = [
    ]
