<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-02-16 03:58
=======
# Generated by Django 2.0.2 on 2018-02-16 03:58
>>>>>>> bbb4124fd5e4476d7c9aad922dadc898bd5fff73

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20180216_0103'),
        ('app', '0016_auto_20180215_0416'),
    ]

    operations = [
    ]
