# Generated by Django 2.0.1 on 2018-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20180216_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, default='TEMP_TEST', max_length=100, null=True),
        ),
    ]
