# Generated by Django 2.0.1 on 2018-02-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180216_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
    ]
