# Generated by Django 2.0.1 on 2018-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_question_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
