# Generated by Django 2.0.1 on 2018-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180216_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_html_content',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
    ]
