# Generated by Django 2.0.1 on 2018-02-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_question_is_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='', max_length=700),
        ),
    ]
