# Generated by Django 2.0.2 on 2018-02-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_question_toolbox'),
        ('app', '0017_merge_20180215_2258'),
    ]

    operations = [
    ]
