# Generated by Django 2.0.1 on 2018-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='guide_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
