# Generated by Django 2.0.1 on 2018-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180224_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_templ',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
