# Generated by Django 2.0.1 on 2018-02-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_question_content_templ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_templ',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
