# Generated by Django 2.0.1 on 2018-03-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180225_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxuser',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
