# Generated by Django 2.0.1 on 2018-07-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20180322_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
